# Generated by Django 4.2.1 on 2023-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_vark',
            field=models.BooleanField(default=True),
        ),
    ]
