# Generated by Django 4.2.1 on 2023-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_question_is_vark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vark_model',
            field=models.CharField(default='', max_length=10),
        ),
    ]
