# Generated by Django 5.0.6 on 2024-05-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_question_choices_alter_student_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('low', 'LowLevel'), ('medium', 'MediumLevel'), ('advanced', 'AdvancedLevel')], default='low', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='vark_model',
            field=models.CharField(default='', max_length=30),
        ),
    ]
