# Generated by Django 5.0.6 on 2024-05-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_level_alter_student_vark_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('LowLevel', 'LowLevel'), ('MediumLevel', 'MediumLevel'), ('AdvancedLevel', 'AdvancedLevel')], default='low', max_length=30),
        ),
    ]
