# Generated by Django 4.0.1 on 2024-05-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_enrollment_status_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
    ]
