# Generated by Django 5.0.6 on 2024-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_course_end_date_remove_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
